### PR TITLE
Borderless Window display mode additions and fixes, timer stats improvements

### PR DESCRIPTION
**Pull request by SRSaunders**
This is a medium-sized contribution that adds a number of display mode features and fixes bugs in mode switching on supported platforms.  I have marked it as Beta not so much from a quality perspective (it's been heavily tested on my multi-monitor Win32/linux/Mac machines), but it slightly changes behaviours for window placement and better defines the meaning of "current monitor" mode.  I would like to see if others find this work useful and it would certainly benefit from other eyes as well as testing on other machine setups.  Here are the changes:

1. Extends support for multi-monitor Borderless (-1) as well as Current monitor (-2) modes across all platforms: Win32, SDL2 (linux, macOS).
2. Adds a User Interface for selecting Borderless and Current Monitor modes on Win32 and SDL2 (linux and macOS).  Note that Borderless window size and location are still defined by cvars (or by dragging and resizing on SDL2/macOS using invisible edges) since user needs are quite specific in multi-monitor setups, and defining a UI for that aspect seemed overkill.
3. Defines "current monitor" for current monitor mode -2 to be the monitor hosting the center of the non-fullscreen window (bordered or borderless) vs. the current less deterministic approach.  Defines current monitor mode to be "display in fullscreen mode using the desktop settings (resolution and refresh rate)" of the "current monitor".
4. Defines the default non-fullscreen window location of r_windowX = -1, r_windowY = -1 which now means centred on monitor 1.  The game will start up in this position when in windowed mode unless the cvars are changed in the console or by moving the window via the UI.  Once the window is moved, the new location will be respected between runs.
5. Fixes issue where window position and size cvars were updating on SDL2 for fullscreen modes - now suppressed.
6. Implements window location cvar update suppression for spurious changes caused by window manager peculiarities when switching modes (e.g. fullscreen on and off, border on and off, fullscreen switching between monitors, etc).  Cvar updates are not suppressed when moving the window by dragging or via the console (e.g. cvar edits +  vid_restart).
7. Now sets fullscreen display frequency following initial startup with SDL2 (linux, macOS) - was missing previously.
8. Improves error handling and recovery from bad parameters - e.g. if cvars define the window position outside of desktop it now falls back to centred on monitor 1 without relying on the window manager to determine the location.
9. Works around an SDL2 issue where the cvar-defined initial window position was changed by various window manager policies especially on multi-monitor setups.  Now the defined cvar position is respected on initial startup.  This is especially important for borderless window mode on multi-monitor setups.
10. Works around another SDL2 issue where fullscreen screen size is sticky on initial window creation and resists resizing when going back to windowed modes after launch - while not seen on macOS, it was a problem on linux.  Issue solved.
11. gfxInfo now supports all display modes (borderless, current monitor) and shows display frequency for all modes.
12. Fixes issue where ImGUI was not updating on window resize events - was missing resize notify in SDL2 event handler.
13. Improves accuracy and correctness of ImGUI timer stats.  Also adds support for proper colouring in vsync mode.  If vsync is enabled and frame rate is at the vsync rate, stats will now be coloured normally (yellow or white).  Previously if the vsync rate was less than the game rate, ImGui frame rate and stats would always be marked red as under target.
14. Added support for dynamic switching of vsync mode with Vulkan renderer for all platforms: Win32 and SDL2.
15. Aligned SDL2 bpp depth checking and mode filtering with Win32 code (e.g. eliminate modes < 720 height).
16. Disabled restriction on Win32 mandating only 60 or 120 Hz display refresh rates - not sure why this was there.
17. UPDATED: For SDL2/SDL1 always grab mouse when in fullscreen, matching behaviour seen on Win32.
18. UPDATED: Align alt-enter shortcut to toggle Current Monitor fullscreen mode -2 on both SDL2 and Win32.

There may be additional small bug fixes here and there that I have not listed above, but that's the gist of it.

Please give this a try and I welcome feedback or potential improvements.  If this work is found to be useful, perhaps it could be incorporated into the master branch following testing and validation by others.

One more thing: While most of these changes do not apply to SDL1, I want to make sure that I have not broken the build on that setup.  I don't have any SDL1 machines to test on, so feedback from anyone willing to regression test would be great.

### CODE REVIEW

**Comment by RobertBeckebans** [comment]
Happy New Year Steve! I'm going to review this in January but can't promise when it gets merged.
Thanks for your pull request :)

I will do less coding in 2022 and focus more on documentation though video episodes on certain RBDOOM-3-BFG topics like TrenchBroom or the upcoming Assimp -> md5mesh/anim pipeline.

Kind regards, Robert

**Comment by SRSaunders** [comment]
Hi Robert - and a Happy New Year to you as well!  I would also like to offer my belated congratulations on your 1.3 release with all the pre-baked lighting files - an excellent accomplishment.

No worries regarding the above pull request.  It was meant as a possible contribution that may line up with your goals for a 1.4 release in the future - you mention borderless mode in your plan file and I thought this might be a step in that direction, along with killing off some bugs in the process.  This request can wait until you have time to look at it - no rush.

I have one small additional pull request that I plan to submit soon.  I have been working with the MoltenVK project re Vulkan timestamp accuracy on Apple M1 machines.  A coming pull request here will line up with that work and also support better GPU vendor detection including Apple Silicon GPUs.

After that I don't plan any additional work unless there are bugs to fix in areas I have worked on.  Given your goals for this year I will pause any new work until you start a new project phase.

**Comment by BielBdeLuna** [comment]
great set of changes! looking forward for it!

**Comment by RobertBeckebans** [comment]
I found several issues with this branch:

* Borderless Window should not be allowed to have a resolution smaller than the monitor resolution
* Probably Current Monitor is actually what gamers consider to be Borderless Windowed mode. It should be fullscreen but easy to escape from into Discord
* We shouldn't display odd display frequencies like 23Hz, 24Hz. Only 60Hz, 120Hz and probably 144Hz should be supported. I'm not sure about the 144Hz tho because the gamecode has to run properly with it so physics aren't breaking
* Alt-Enter should toggle between Windowed Mode and either full screen mode or full screen borderless windowed mode. It is important to be able to leave fullscreen mode into windowed mode quickly for mapping so you can still work with all programs on the Desktop like TrenchBroom and Blender and you have still the engine running in the background so you can iterate and preview light changes from the editor instantly.

**Comment by RobertBeckebans** [comment]
I have 3 monitors with 1440p and the primary one is a 144Hz monitor. I get way too many options right now.
It takes like a minute to get until my preferred setting 2560x1440@120.

rbdoom-3-bfg-20220212-103528-001

rbdoom-3-bfg-20220212-103825-002

**Comment by SRSaunders** [comment]
Thanks @RobertBeckebans for the feedback.

1. The refresh rate issue is a simple fix - I have made the changes to restore filtering for Windows, and added the same filter for SDL (Linux & macOS) which was never there.  The permitted frequencies are now 60, 120, and 144 Hz.  I had opened this up for my testing (one of my monitors is 75 Hz 2560 x 1440), but I guess the list gets too large.
2. The definition of Current Monitor Fullscreen and Borderless Mode are interesting.  In my beta branch Current Monitor = true fullscreen mode with mouse always captured on a **single monitor** at its desktop resolution.  Borderless Window = any resolution up to the full **multi-monitor** desktop size (i.e. rendering across multiple displays), and the mouse can be released to other non-game monitors using console escape (e.g. good for Discord, debugging, mapping, etc).  However, before making any changes, I need to understand whether multi-monitor spanning is important to your audience or not.  If not, then I completely agree that the Current Monitor mode or a **single monitor** Borderless Fullscreen mode with mouse release may be what your audience is looking for.  Please let me know what your preference is and I can code up a solution pretty quickly for you to try out.
3. In my current branch, Alt-Enter toggles between windowed and current monitor fullscreen.  Depending on the answer to item 2 above, I could modify this behaviour to toggle between windowed and single monitor borderless fullscreen mode.

I appreciate you looking at this Beta pull request, and would be happy to modify it based on your feedback.

**Comment by SRSaunders** [comment]
Hi Robert, I have changed the behaviour based on your original feedback above.  I hope this is closer to convention and closer to what you are looking for:

1. Restored refresh rate filtering (60, 120, 144 Hz) for Windows, and added refresh rate filtering for SDL (linux, macOS).
2. Redefined Borderless Window mode (-2) to match nomenclature and behaviour conventions and simplified its presentation in the GUI selector.  This mode is now a fullscreen borderless window on the current monitor, and supports mouse release using console escape (~) when in a game.
3. Renamed and removed Custom Borderless mode (-1) from the GUI selector.  This mode continues to support multi-monitor spanning but is now a custom console option only.
4. Alt-enter now exits any fullscreen mode and toggles between windowed mode and fullscreen borderless windowed mode for quick transitions.

I think these changes should support the goals you mentioned above.  Please review and let me know if this helps.

**Comment by davidebeatrici** [comment]
I believe the refresh rate should be a separate setting.

**Comment by SRSaunders** [comment]
Remove this pull request for now.  Timer improvements have already been merged, and borderless display needs some additional work targeting the new code base before resubmitting.

**Pull request closed without merging**
