### PR TITLE
[Vulkan] Integrate VMA allocator for Image/Buffer Memory and Fix Staging Buffer fragmentation

### LINKED ISSUE #724: [Vulkan] maxMemoryAllocationCount limit hit on Windows for AMD cards
[Vulkan] ERROR location=0x4e9256cc code=0, layerPrefix='Validation'] Validation Error: [ VUID-vkAllocateMemory-maxMemoryAllocationCount-04101 ] Object 0: handle = 0x1b21eab0200, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x4e9256cc | vkAllocateMemory: Number of currently valid memory objects is not less than the maximum allowed (4096). The Vulkan spec states: There must be less than VkPhysicalDeviceLimits::maxMemoryAllocationCount device memory allocations currently allocated on the device (https://vulkan.lunarg.com/doc/view/1.3.231.1/windows/1.3-extensions/vkspec.html#VUID-vkAllocateMemory-maxMemoryAllocationCount-04101)
Assertion failed!

This is potentially a difficult issue for Windows Vulkan on AMD cards.  My 6600XT has a maxMemoryAllocationCount limit of 4096 on Windows, but no such limit on Linux and macOS.  The game runs well using Vulkan on Linux and macOS, but I can't proceed on Windows due to this limit.  This is a blocking failure mode with an in-game assert.

### PR DESCRIPTION
**Pull request by SRSaunders**
This fixes #724 and enables Vulkan for AMD cards on Windows.

1. Integrates VMA side-by-side with NVRHI's built-in allocator.  VMA is used for texture (image) and rendering buffer (vertex, index, uniform) allocations on Vulkan.  VMA manages memory allocations to prevent exceeding device and/or driver limits (maxMemoryAllocationCount). The NVRHI pass-through allocator is still used for rendering pass command buffers, constant buffers and staging buffers of which there are many fewer.  NVRHI is not modified in this integration.
2. Fixes NVRHI upload (staging) buffer fragmentation by setting larger default block sizes during command list creation.  Previous default was the max of 65 Kbytes or the size of request, new default is 65 Mbytes.  Thousands of small buffers were being allocated which contributed to exceeding device allocation count limits.  The new default prevents this.
3. Several new cvars are defined that control memory allocation: a) **r_vmaDeviceLocalMemoryMB** sets the VMA block size for GPU-side allocations - default is 256 MB, b) **r_vmaAllocateBufferMemory** is a boolean that controls whether VMA is used to allocate buffer memory objects or not - default is 1 (true), note that texture (image) memory is always allocated by VMA, and c) **r_uploadBufferSizeMB** is used to set the staging buffer size - default is 64 MB.
4. A new CMake option is defined, **USE_VMA** (default ON) which controls whether VMA is included at build time.  You can set **USE_VMA=OFF** to completely disable VMA and not link to it.  The code then defaults back the the NVRHI built-in allocator for all objects.
5. The latest version of VMA https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator is included as a new library under the libs directory.  I included the whole distro by default, but this can be pruned down to the include directory and license files if desired.

In addition, this PR fixes a few other issues:

6. Improves Vulkan SDK component detection (dxc SPRIV on all platforms, MoltenVK for macOS) by leveraging cmake's FindVulkan.cmake **OPTIONAL_COMPONENTS** option.  This simplifies the CMakeLists.txt code but still supports the **DXC_SPIRV_EXECUTABLE** setting for manually defining the location of the dxc for SPIRV executable.
7. Fixes posix `pthread_yield()` and `readdir_r()` deprecations on linux.  All posix platforms now use `sched_yield()` and `readdir()` instead.  Note that glibc's readdir() is thread safe across different directory streams and can be used.
8. **UPDATE:** Fixes Vulkan validation errors caused by the new SSAO compute shader reading storage images without format information.  This fix turns on the `shaderStorageImageReadWithoutFormat` device feature to suppress this error.

**Note:** The **r_vmaAllocateBufferMemory** cvar option was put in place as "future proofing" for potential implementation of ray tracing that requires the **VK_KHR_buffer_device_address** feature.  One downside of the VMA buffer allocation integration is that it leverages NVRHI's `createHandleForNativeBuffer()` method which does not set the buffer device address in the resulting **IBuffer**.  This is in contrast to the `createBuffer()` method which does set the field inside **IBuffer**.  NVRHI can be easily patched with this improvement (I have a patch for this available if desired), but if we are keeping NVRHI "vanilla" then this cvar option can be set to false (0) which will cause buffer objects to be allocated with `createBuffer()` which supports the buffer device address feature.  Turning off VMA for buffer objects is not such a big deal as there are many fewer of those (10s) versus textures (1000s), and device limits should not be exceeded.  Something to think about for the future.

### CODE REVIEW

**Comment by RobertBeckebans** [comment]
I'm already playtesting it. Thank you that is a really nice birthday gift :)  👍

**Comment by SRSaunders** [comment]
You're very welcome.  Happy Birthday Robert!

**Comment by RobertBeckebans** [comment]
I bought a new AMD notebook for work so I can test this branch better. It has a Radeon 6600M GPU. The changes look good so far and Stephen Pridham also reviewed them.

**Comment by SRSaunders** [comment]
Thanks for reviewing and merging.  Glad to have multiple sets of eyes on this to avoid breakage.

**Pull request merged**
