### PR TITLE
SEA Initial Commit (Lots of stuff)

### PR DESCRIPTION
**Pull request by SEAGitUser**
Removed legacy OGL matrix code, replaced with idRenderMatrix.
Shadow map code optimisations.
RenderView structure remanufactoring.
Misc fixes, cosmetics ))

### CODE REVIEW

**Comment by SEAGitUser** [comment]
SEA Initial comment :)

**Comment by BielBdeLuna** [comment]
pretty interesting

**Comment by Jarvik7** [comment]
You'll probably want to break this down into smaller commits if you hope to get it accepted.
RBDOOM project is pretty conservative.

**Comment by BielBdeLuna** [comment]
with your last commit I can't compile past the models:

> `/home/biel/games/src/SEAGitUser-RBDoom3BFG/neo/renderer/Model.cpp: In member function ‘virtual int idRenderModelStatic::Memory() const’:
> /home/biel/games/src/SEAGitUser-RBDoom3BFG/neo/renderer/Model.cpp:144:33: error: ‘struct idTriangles’ has no member named ‘UsedCPUMemory’
>    totalBytes += surf->geometry->UsedCPUMemory();
> `

**Comment by RobertBeckebans** [comment]
Interesting stuff. I keep this in mind for later merging. I cannot merge this into master because this branch
https://github.com/RobertBeckebans/RBDOOM-3-BFG/tree/vkdoom3-merge  will be merged first.
The vkdoom3-merge is based on Dustin Lands Vulkan port which incorporates a ton of changes that affect the OpenGL rendering as well and really lots of stuff was refactored.
I'm really busy with a commercial game project at the moment but I hope to find some time to work on the Vulkan stuff as soon as possible during the christmas holidays.

**Comment by SEAGitUser** [comment]
BielBdeLuna : oops! rename it to CPUMemoryUsed();

**Comment by BielBdeLuna** [comment]
ok

**Pull request closed without merging**
