### PR TITLE
Remove X11_XCB dependencies for Linux and macOS

### PR DESCRIPTION
**Pull request by SRSaunders**
Disabled X11_XCB build dependencies for Linux and macOS.  Not needed since these platforms use SDL2.  Fixes issues raised in #596.  Also applied minimal changes to make CMakeLists.txt and Vulkan platform-specific code consistent:

For Linux and macOS:
- CMakeLists changed to skip X11_XCB references and Vulkan platform-specific definitions for Linux and macOS (since SDL2 used instead)

For other UNIX-style platforms:
- CMakeLists changed to use X11_XCB_INCLUDE_DIR instead of X11_XCB_INCLUDE_DIRS (thanks to @tomgreen66)
- CMakeLists changed to define VK_USE_PLATFORM_XCB_KHR instead of VK_USE_PLATFORM_XLIB_KHR
- Added VK_USE_PLATFORM_XCB_KHR guards to platform-specific content in posix_public.h
- Added VK_USE_PLATFORM_XCB_KHR comment to `CreateSurface()` in RenderBackend_VK.cpp

For Windows:
- Replaced _WIN32 with VK_USE_PLATFORM_WIN32_KHR in `CreateSurface()` in RenderBackend_VK.cpp

Tested on macOS Big Sur, Linux Manjaro, and Windows 10.

### CODE REVIEW

**Comment by DanielGibson** [comment]
RBDoom3BFG only has two general platform backends (esp. from the window- and event-handling perspective): Windows and SDL.
So there's no point in treating other X11 platforms (like *BSD) different than Linux

**Comment by SRSaunders** [comment]
Thanks, your comment captures my conundrum.  There are two approaches possible to clean this up:  a) leave the pre-existing X11 code in place while cleaning up dependencies and slightly improving consistency, or b) remove the platform-specific X11 code and commit to Win32 and SDL (currently linux and macOS) only.

In my pull request I chose the more conservative former approach since I am relunctant to remove code without a complete understanding of past reasons or potential future use.  The second approach, while not drastic, would permanently remove the X11 hooks:

1. Completely remove the X11_XCB logic and surrounding code block (including `VK_USE_PLATFORM_WIN32_KHR`) from CMakeLists, and delete the FindX11_XCB.cmake support file
2. Replace the `VK_USE_PLATFORM_WIN32_KHR` #include with a `_WIN32` #include in qvk.h and remove the remaining `VK_USE_PLATFORM_X*` #include sections from the file
3. Remove all XCB references from the posix_public.h file
4. Remove the `VK_USE_PLATFORM_WAYLAND_KHR` and `VK_USE_PLATFORM_X*` #include sections from `CreateSurface()` in the RenderBackend_VK.cpp file, leaving only `_WIN32`,  `__linux__`  and `__APPLE__` #includes
5. Note that even after this, the remainder of the Vulkan code uses `#ifdef __linux__` and `#ifdef __APPLE__` for enabling the Vulkan SDL portions of the code, so currently it is not truly portable to other *BSD platforms.

I would be happy to update my pull request with the latter approach if other maintainers agree.  Please let me know.

**Comment by DanielGibson** [comment]
Oops, looks like there indeed is a little bit of X11/XCB-specific code (I'm not really familiar with the Vulkan code in RBDoom3BFG).

No idea why, maybe Robert copy-pasted that from somewhere..

Anyway, if at all possible I'd suggest to have exactly two cases in that ` CreateSurface()` function: `_WIN32` with the code it already has, and the code with `SDL_Vulkan_CreateSurface()` for *all* other platforms, and remove all includes of x11 or xcb headers from the RBDoom3BFG code.
If that requires adapting some other source files like qvk.h, that should be done (maybe you're lucky and those includes guarded by `VK_USE_PLATFORM_XCB_KHR` etc aren't even used

**Comment by SRSaunders** [comment]
Thanks again.  You are suggesting exactly what option b) describes above.  Fortunately the guarded X11 and XCB #includes in qvk.h are not used in the code so they can be removed easily - perhaps leftovers from initial Vulkan porting work.  And good suggestion re making the Vulkan SDL `#if defined(__linux__) || defined(__APPLE__)` stuff generic using a CMakeLists defined variable.

I am curious about @RobertBeckebans' opinion on this.  If he agrees and comments here, I will proceed.

**Comment by RobertBeckebans** [comment]
If SDL_Vulkan_CreateSurface is used then you don't need to call vkCreateXcbSurfaceKHR. 
Windows should use VK_USE_PLATFORM_WIN32_KHR and vkCreateWin32SurfaceKHR.
All other platforms should use SDL and SDL_Vulkan_CreateSurface which should wrap the proper adaption to X11, Wayland or whatever comes up in the future.

**Comment by RobertBeckebans** [comment]
I guess it's fine to remove all explicit CMake and code references to X11/XCB-specific code.

**Comment by SRSaunders** [comment]
Removed X11_XCB legacy code as discussed above.  Introduced `VULKAN_USE_PLATFORM_SDL` CMake variable to generalize enablement of SDL code, permitting additional SDL-capable OS support in the future.  Currently this CMakeLists variable is defined only for linux and macOS.

Tested on macOS Mojave and Big Sur, Linux (Manjaro), and Windows 10.

**Pull request merged**
