### PR TITLE
Sync points revisited

### PR DESCRIPTION
**Pull request by stephenap07**
I didn't want to have to increase my frame data by 50%, so I added an option to use 2 buffers of frame data without gpu artifacts happening.

This doesn't quite work well with vulkan yet. I need help with that one. I don't see a reason to need that 3rd frame buffer data in order to prevent those gpu artifacts, it should be viable to use however many frames you want.

### CODE REVIEW

**Comment by stephenap07** [comment]
@RobertBeckebans @SRSaunders

**Comment by SRSaunders** [comment]
I tried this on Vulkan and it doesn't work quite yet.  I will study your changes for DX12 and see if I can help with Vulkan.

**Comment by RobertBeckebans** [comment]
I can understand why @stephenap07 wants the vertex cache to be only double buffered. There is another branch for bindless rendering and he many changes to the vertex cache and doubled buffered the commandlists so the new code.

I still to to change Optick to print the GPU frames for a better understanding what is going on.

**Comment by SRSaunders** [comment]
I looked deeper into this and found something quite interesting.  For DX12, Stephen's new implementation is really the same as mine, at least for triple buffering.  Under the hood, NVRHI implements `m_NvrhiDevice->waitEventQuery()` as a d3d12 graphics queue frame fence, just like in Stephen's code.  For Vulkan, NVRHI uses timeline semaphores instead of vkQueueSubmit's fence - in fact you can't even get at the Vulkan queue submit fence using NVRHI, it doesn't use it and the API does not expose it.  So in summary, you can either use d3d12 fences directly or `waitEventQuery()` for DX12 sync - they are equivalent, but you must use `waitEventQuery()` for Vulkan sync.

I measured DX12 timings for Stephen's d3d12 implementation (NUM_FRAME_DATA = 3, com_fixedTic = 1) and for my `waitEventQuery()` approach on DX12:  they both clock in at 316 fps for the hangar scene, i.e. identical as you would expect given my comments above.  For NUM_FRAME_DATA = 2, Stephen's implementation came in somewhere around 40-80 fps, but there was instability in the vertex cache with artifacts visible, at least on my AMD GPU.

On the Vulkan side of things with NUM_FRAME_DATA = 2, I implemented an equivalent solution to Stephen's d3d12 design, i.e. for triple buffering wait on the previous queue completion, for double buffering wait on the current queue completion.  This simply means that `waitEventQuery()` happens first for NUM_FRAME_DATA=3, and last for NUM_FRAME_DATA=2.  The new Vulkan code looks like this (no other changes are needed vs. the current master branch), and gives stable results for NUM_FRAME_DATA = 3 or = 2 with no artifacts or problems with the vertex cache.  However, there is a clear performance difference between the two given the higher amount of CPU/GPU parallelism that can occur with triple vs. double buffering.

If you are interested, I could push this as a PR for the Vulkan side of things. AFAIK the same thing could be done for DX12, but I will leave that up to you and Stephen on how you want to proceed (i.e. d3d native or nvrhi portable approach).

```
void DeviceManager_VK::Present()
{
	if constexpr( NUM_FRAME_DATA > 2 )
	{
		// SRS - Sync on previous frame's command queue completion vs. waitForIdle() on whole device
		m_NvrhiDevice->waitEventQuery( m_FrameWaitQuery );
		m_NvrhiDevice->resetEventQuery( m_FrameWaitQuery );
		m_NvrhiDevice->setEventQuery( m_FrameWaitQuery, nvrhi::CommandQueue::Graphics );
	}

	vk::PresentInfoKHR info = vk::PresentInfoKHR()
							  .setWaitSemaphoreCount( 1 )
							  .setPWaitSemaphores( &m_PresentSemaphore )
							  .setSwapchainCount( 1 )
							  .setPSwapchains( &m_SwapChain )
							  .setPImageIndices( &m_SwapChainIndex );

	const vk::Result res = m_PresentQueue.presentKHR( &info );
	assert( res == vk::Result::eSuccess || res == vk::Result::eErrorOutOfDateKHR || res == vk::Result::eSuboptimalKHR );

	if( m_DeviceParams.enableDebugRuntime || m_DeviceParams.vsyncEnabled )
	{
		// according to vulkan-tutorial.com, "the validation layer implementation expects
		// the application to explicitly synchronize with the GPU"
		m_PresentQueue.waitIdle();
	}
	
	if constexpr( NUM_FRAME_DATA < 3 )
	{
		// SRS - Sync on current frame's command queue completion vs. waitForIdle() on whole device
		m_NvrhiDevice->resetEventQuery( m_FrameWaitQuery );
		m_NvrhiDevice->setEventQuery( m_FrameWaitQuery, nvrhi::CommandQueue::Graphics );
		m_NvrhiDevice->waitEventQuery( m_FrameWaitQuery );
	}
}

```

**Comment by RobertBeckebans** [comment]
I'm closing this because most of this code was merged by #761

**Pull request closed without merging**
