### PR TITLE
Prevent vanilla .resource maps to be reloaded

### PR DESCRIPTION
**Pull request by MadDeCoDeR**
This will allow RBDOOM to load .resource mods that affect vanilla maps like : [https://www.moddb.com/mods/classic-rbdoom-3-bfg-edition/addons/doom-3-bfg-hi-def-resource-edition](url).

### CODE REVIEW

**Comment by RobertBeckebans** [comment]
I already added glslang as a Git submodule in the newer vulkan branch: https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/e0a397e544113fb0a296759be936cc9e529190bf

This ensures that a version of glslang is included which compiles the generated Vulkan GLSL shaders. The glslang code with the newest Vulkan SDK on Windows failed.

**Comment by RobertBeckebans** [comment]
Could you split the pull request and reformat code with the provided Astyle .bat?

**Comment by MadDeCoDeR** [comment]
Ok now ?

**Comment by RobertBeckebans** [comment]
I integrated this patch manually because I wanted to avoid the hassle with the Vulkan directory. It's part of the current PBR2 development branch.

**Comment by RobertBeckebans** [comment]
I tested this with the UltimateHD mod and it is a nice loading boost after dying.

**Comment by MadDeCoDeR** [comment]
Was in .resources or raw files ? (Probably raw)
In general it only checks also the maps directory for .resources instead of relying for the name in order to get the relative path. Maybe it's something else.(Better check logfiles for more info)

**Pull request closed without merging**
