### PR TITLE
Dhewm3 leak fixes

### PR DESCRIPTION
**Pull request by y2keeth**
Dhewm3 leak fixes

### CODE REVIEW

**Comment by BielBdeLuna** [comment]
what fixes does this incorporate?

**Comment by y2keeth** [comment]
https://github.com/dhewm/dhewm3/commit/befe732dbb60d5b408ccb86515a7d91a2d55fbb0

**Comment by dsalt** [comment]
This needs some clean-up and a rebase.

**Comment by y2keeth** [comment]
as much as i suck at coding, I suck at github even more

**Pull request closed without merging**
