### PR TITLE
Add support for mikktspace

### PR DESCRIPTION
**Pull request by stephenap07**
I added support for mikktspace for generating tangent spaces for new assets.

Normal map rendered in blender evee:
image

How it looks in doom 3 by default:
image

How it looks with mikktspace:
image

Here's a test asset if you'd like to quickly test this yourself:
https://www.dropbox.com/sh/594hsrpioc8ts53/AACBCFwgH2J3gkO0X4779pMRa?dl=0

### CODE REVIEW

**Comment by BielBdeLuna** [comment]
excellent!

**Comment by Arl90** [comment]
I love this very much. Thank you!

**Comment by stephenap07** [comment]
@Arl90 You're welcome! I plan to contribute more in the future.

**Comment by RobertBeckebans** [comment]
Very good! I'm going to review this deeper next week. I'll probably add a mechanism where you can define mikktspace usage per asset.

**Comment by BielBdeLuna** [comment]
great!

**Comment by RobertBeckebans** [comment]
I merged this into the master and added some extra code so that mikktspace is only used for newer assets (newer than 2016.1.1) or if you explictly specify it in the materials. So mikktspace is a new idMaterial keyword.

https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/e7e2786b76d96103f3f8c74a4222455322216e55

**Comment by RobertBeckebans** [comment]
New binaries for testing are here: https://drive.google.com/open?id=1GNMXTO-cwqQVwtAYBADY0rvfBTekSoJW

**Pull request merged**
