### PR TITLE
[Vulkan] Build fixes for linux/macOS and update Vulkan descriptor selectors for BinkDec shaders

### PR DESCRIPTION
**Pull request by SRSaunders**
Fixes multiple linux/macOS issues:
1. fix **compileshaders.cmake** to reference `USE_VULKAN` vs. the removed `USE_NVRHI_VULKAN` build setting
2. add missing `override` option for `InitFromFile()` in **Model_local.h**, otherwise many clang compiler warnings
3. restore `FFMPEG` and `BINKDEC` cmake options to be independent of `USE_INTRINSICS_SSE`.  These AV decoder settings are orthogonal to x86-specific intrinsics and should be independently settable for both x86 and non-x86 architectures based on desired build config (i.e. within cmake scripts).
4. fix Vulkan descriptor set selectors within **bink.ps.hlsl** and **binkgui.ps.hlsl** shaders
5. augment `Sys_DefaultBasePath()` within **posix_main.cpp** to also look for the **base** directory within the build path when developing/debugging.  This helps find the **renderprogs2** directory which is now created in the install base path.  Works for macOS Xcode builds and linux/macOS makefile builds.  This is different from VS which can rely on an "adjusted" cwd path for the correct location.  The cwd path on macOS/linux is not adjusted by Xcode or linux IDEs or make/gdb.
6. remove `link_directories(${FFMPEG_LIBRARIES_DIRS})` from CMakeLists since this variable is undefined.   The variable `FFMPEG_LIBRARIES` already consolidates path information for use in `target_link_libraries()`.

Fixes several macOS-specific issues:

1. restore macOS-specific crossing-compiling logic for `USE_PRECOMPILED_HEADERS` and `USE_INTRINSICS_SSE`.  Not sure why these were changed, but current logic is wrong and breaks ability to create macOS universal binaries on x86 and M1 arm machines.  Note that `CMAKE_OSX_ARCHITECTURES` (target arches) is safe and ignored for non-macOS builds.
2. fix support for `USE_MoltenVK` cmake option for NVRHI builds (was broken in new code stream).  This option is useful for building release/standalone game versions that link directly to **libMoltenVK.dylib** vs. **libvulkan.dylib**
3. minor cmake build scripts fix to eliminate extraneous library search paths that caused link warnings with Xcode
4. minor cmake build scripts fix to disable Xcode Metal API validation for release builds - otherwise kills performance
5. delete old macOS-specific cmake build scripts referring to OpenGL
6. explicitly define **dxc** path on macOS so `find_package(DXCspirv)` uses the specified Vulkan SDK location

**UPDATE & BUG FIX (All Platforms):**

1. changed remaining direct Vulkan API calls in **Device_Manager_VK.cpp** to use the NVRHI layer API for consistency
2. fixed vulkan dll unloading bug exposed by removing direct Vulkan API calls in 1 above.  On Windows, the vulkan dll would unload after exiting `CreateDeviceAndSwapChain()` and then the game would crash.  On investigation, this was caused by the `~DynamicLoader` destructor cleaning up the local `dl` variable.  Interestingly, by no longer having any direct Vulkan API calls from the main application, the vulkan dll ref count would drop to zero and Windows would unload the vulkan dll. The solution I am submitting makes the `dl` variable `static` so it hangs around until the application exits, and the vulkan dll is not prematurely unloaded.  Tested on Windows 10, linux Manjaro, and macOS Monterey.

### CODE REVIEW

**Comment by RobertBeckebans** [comment]
I can play the game in 640x480 on my Kubuntu 22.04 but changing the resolution to 2560x1440 gives me a black screen regardless of the target Hz.
Still some progress and a good job! :+1:

**Comment by SRSaunders** [comment]
Good news that your crash on Kubuntu is fixed.  However, can you tell me a bit more about the black screen issue:
1. Do you get a black screen if you start up at 2560x1440 (or other resolutions other than 640x480)?
2. Does the issue occur when changing windowed-mode resolutions within the game? (via menu or via dragging)
3. Does it happen in windowed mode or only fullscreen mode? (e.g. toggling in/out using ALT-enter)
4. Are there any console or validation error messages that would provide any hints at the issue?

**Comment by RobertBeckebans** [comment]
1. Yes but it seems that SDL can't detect my monitor resolution and has something like 2560x1413.
2. Yes
3. Toggling between windowed and fullscreen mode was the same result.
4. Running r_useValidationLayers 2 immediatly quit the engine with an error message that an extension isn't supported but I can't remember right now. I'm on Windows at the moment.

Anyway I just wanted to give you some feedback. I also merged 635-nvrhi5 into the master.
I wish you a Merry Christmas and happy New Year. I'm going offline until 9 January.

**Comment by SRSaunders** [comment]
Happy New Year Robert and thanks for the additional information.

To see if I could reproduce these issues I built a Kubuntu 22.04 USB drive to run on an Intel i7-12700K/Nvidia 3070ti machine (borrowed for testing). I also installed the most recent Nvidia 525.60.11 drivers for linux-64.  Unfortunately I can't reproduce the problems above using this setup.  I can run the game at any resolution my monitor supports (up to 2560 x 1440 @ 60 Hz).  No validation errors are thrown except for the vksurface errors caused by enumerating llvmpipe during device selection - which can be safely ignored since that software device is not selected if a discrete gpu is present.

I am wondering whether the mode list for your monitor is not aligned with the `r_vidMode` setting saved in your D3BFGConfig.cfg file.  Would it be possible to start your game in windowed mode and then use the in-game menu to select a different resolution (i.e. don't use alt-enter).  This will reset the `r_vidMode` setting in your D3BFGConfig.cfg file to be a valid mode for your monitor (alt-enter will not).  After that alt-enter should work properly to switch in and out of fullscreen.

FYI I have made a few small changes to **sdl_events.cpp** and **sdl_vkimp.cpp** to make SDL/linux video mode list filtering consistent with Win32 (32/24 bpp, 60 or 120 Hz, h>=720), and window positioning more consistent when leaving fullscreen into windowed mode (eliminate position drift).  I don't think these changes should have an effect on my test results but I can make them available to you in a branch if you want to test with them.  If they check out or help your situation I can generate a pull request.

**Comment by RobertBeckebans** [comment]
I reverted the shader related changes in CMakeLists.txt because they are added for editing them in Visual Studio.
It is more convenient than in other editors. With this branch I was able to run the game in my native resolution 2560x1440@60 however I also disabled my second monitor for the test.

**Comment by SRSaunders** [comment]
Thanks Robert for looking at these and merging.  I am glad you can now run the game at native resolution on Kubuntu.

The Shader-related stuff was for cleanliness only, not functionality.  At least for me, the Shaders were still visible and editable in VS2019 (and Xcode) by scrolling down in the project browser until you hit the **Shaders** target.  Expanding it reveals all the shaders within their own folder structure.  However, perhaps it's more convenient to also have them grouped with the main code under the **renderer** folder.

I have one more thing I am working on, but not sure if you are interested.  I have found the issue with parallel shader compilation failure on macOS.  It is caused by `pclose()` occasionally emitting a 127 error status based on inability to fork/execute a shell command (either **/bin/sh** itself, or the **dxc** command).  It may be caused by some resource limit on macOS, or perhaps an edge case timing issue which I can't seem to narrow down at the moment.  However, the solution is straight forward and generic - simply re-queue the failed task and retry later (up to a total of 10 times).  Currently I have this solution prototyped and it works well across all my tests, shaves 10 seconds off macOS compile times (down to about 54 sec now), and is generic to all platforms.  However, it would require a change to the **nvrhi/tools** project under your forked repo. Is this something you would consider?  If this was accepted, I would later submit a small PR changing the **compileshaders.cmake** file under your game repo - to remove all macOS-specifics including moving to SPIRV v1.4 for vulkan 1.2 targets (now supported by MoltenVK as part of Vulkan SDK 1.3.231 or later).

**Comment by RobertBeckebans** [comment]
Yeah changes in nvrhi/tools are fine. Just make a separate request for that. Nvidia might also be interested in those changes.
Currently I'm most interested in the SSAO alternative because that is still a major blocker for the upcoming RBDoom 1.5x release.
Otherwise I would try it myself soon.

**Comment by SRSaunders** [comment]
Ok thanks re the shaderCompiler in nvrhi/tools.

Re the SSAO alternative, I tried a few things before without success, but will try again.  If I run into roadblocks I will message you and perhaps you could lend a hand or take over.

**Pull request merged**
