### PR TITLE
Update Constant Buffer Usage For Performance + Fix TAA for Vulkan

### LINKED ISSUE #723: [Vulkan] TAA Antialiasing does not work on Vulkan for Linux and macOS
Need to disable TAA or get a pipeline layout failure on Linux and macOS, likely on Windows as well (to be verified).

The following fatal errors occur when moving in loaded map (something to do with motion vectors, and I suspect the D24S8 or D32S8 depth/stencil textures):

[Vulkan] ERROR location=0x45717876 code=0, layerPrefix='Validation'] Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-00756 ] Object 0: handle = 0x11504e618, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x45717876 | Shader uses descriptor slot 2.128 (expected `VK_DESCRIPTOR_TYPE_SAMPLER, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`) but not declared in pipeline layout The Vulkan spec states: layout must be consistent with all shaders specified in pStages (https://vulkan.lunarg.com/doc/view/1.3.224.1/mac/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-00756)

[Vulkan] ERROR location=0x45717876 code=0, layerPrefix='Validation'] Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-00756 ] Object 0: handle = 0x11504e618, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x45717876 | Shader uses descriptor slot 1.1 (expected `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE`) but not declared in pipeline layout The Vulkan spec states: layout must be consistent with all shaders specified in pStages (https://vulkan.lunarg.com/doc/view/1.3.224.1/mac/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-00756)

[Vulkan] ERROR location=0x45717876 code=0, layerPrefix='Validation'] Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-00756 ] Object 0: handle = 0x11504e618, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x45717876 | Shader uses descriptor slot 1.0 (expected `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE`) but not declared in pipeline layout The Vulkan spec states: layout must be consistent with all shaders specified in pStages (https://vulkan.lunarg.com/doc/view/1.3.224.1/mac/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-00756)

[Vulkan] ERROR location=0xffffffff9888fef3 code=0, layerPrefix='Validation'] Validation Error: [ VUID-vkCmdDrawIndexed-None-02697 ] Object 0: handle = 0x6dd5c10000003682, type = VK_OBJECT_TYPE_PIPELINE; Object 1: handle = 0x6fa2a20000003681, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0x9888fef3 | vkCmdDrawIndexed(): The VkPipeline 0x6dd5c10000003682[] (created with VkPipelineLayout 0x6fa2a20000003681[]) statically uses descriptor set (index #2) which is not compatible with the currently bound descriptor set's pipeline layout (VkPipelineLayout 0x6fa2a20000003681[]) The Vulkan spec states: For each set n that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a descriptor set must have been bound to n at the same pipeline bind point, with a VkPipelineLayout that is compatible for set n, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://vulkan.lunarg.com/doc/view/1.3.224.1/mac/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-02697)

[Vulkan] ERROR location=0xffffffffa44449d4 code=0, layerPrefix='Validation'] Validation Error: [ VUID-vkCmdDrawIndexed-None-02699 ] Object 0: handle = 0x928f0f000000357b, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xa44449d4 | VkDescriptorSet 0x928f0f000000357b[] encountered the following validation error at vkCmdDrawIndexed time: Attempting to validate DrawState for binding #0  which is an invalid binding for this descriptor set. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid if they are statically used by the VkPipeline bound to the pipeline bind point used by this command (https://vulkan.lunarg.com/doc/view/1.3.224.1/mac/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-02699)

[Vulkan] ERROR location=0xffffffffcde11083 code=0, layerPrefix='Validation'] Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound ] Object 0: handle = 0x1093dfe58, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xcde11083 | vkCmdDrawIndexed(): VkPipeline 0x6dd5c10000003682[] uses set #2 but that set is not bound.

### PR DESCRIPTION
**Pull request by stephenap07**
Vulkan is now similar in performance to d3d12 with these changes. One difference is that noclipping around a map will result in a memory overflow due to the relatively low `c_MaxRenderPassConstantBufferVersions`. I've made it so that each binding layout has its own constant volatile buffer.

This should fix #723.

I've also updated NVRHI to allow for sub-ranging Constant buffers as well as mapping buffers in sub-ranges. This will allow for more flexible constant buffers. I was thinking of moving the joint buffer back into a regular buffer object instead of a structured buffer in a texture slot.

### CODE REVIEW

**Comment by RobertBeckebans** [comment]
Ok I tested this branch. There are some issues so far.

1. The random floating mesh error is back #660 and it also happens with the DX12 graphics backend.
2. The performance is not as good as DX12. Especially with com_fixedTic 0 I get about 100 fps less in the mars_city1 hangar scene.
3. If you start the engine with +set r_graphicsAPI vulkan +set r_useValidationLayers 2 you will still get a ton of validation errors concerning the draws outside of an RenderPass. See #714 #720

Besides that the Vulkan rendering is in better shape than ever before :)

**Comment by stephenap07** [comment]
I haven't been able to reproduce that floating mesh error, but I changed it so the binding sets are cache more aggressively. That's the more likely reason for floating meshes. I can add another condition to invalidate the cache.
Whenever the command list writes to a buffer, it ends the renderpass for Vulkan hence running into that validation error. I'm looking for alternatives.

**Comment by stephenap07** [comment]
Just commenting out `endRenderPass` in the vulkan backend fixes the validation error. I haven't run into any issues with this change, but I'm not entirely sure why ending a render pass is necessary here in the first place and not confident in committing this.

```
diff --git a/src/vulkan/vulkan-buffer.cpp b/src/vulkan/vulkan-buffer.cpp
index 4217d7d..8c1d6ea 100644
--- a/src/vulkan/vulkan-buffer.cpp
+++ b/src/vulkan/vulkan-buffer.cpp
@@ -385,7 +385,7 @@ namespace nvrhi::vulkan
 
         assert(m_CurrentCmdBuf);
 
-        endRenderPass();
+        //endRenderPass();
 
         m_CurrentCmdBuf->referencedResources.push_back(buffer);

```

**Comment by stephenap07** [comment]
OK. I figured it out. Just set the graphic state again whenever the constant buffer is written to. No more validation errors, no need to change NVRHI.

**Comment by SRSaunders** [comment]
Great result.  This works very well - tested on macOS Monterey.  No need to disable state caching and TAA works for Vulkan.  In addition to fixing #723, this likely also fixes #714 and #720.  No validation errors other than shader performance and frame buffer suboptimal warnings.

Performance is still lacking with serialization of CPU and GPU work.  But that is a different problem for another day.

**Comment by RobertBeckebans** [comment]
I tested the last version but it makes things a bit worse. I have many flickering problems with the md5 models in both DX12 and Vulkan. This is easy to reproduce in the bathroom scene in alphalabs2. If I play a few minutes I get this:

rbdoom-3-bfg-20221120-122020-002
rbdoom-3-bfg-20221120-122104-009
2022-11-20 12_16_58-DOOM 3_ BFG Edition

**Comment by RobertBeckebans** [comment]
I merged this into 635-nvrhi5. The problem was or still is if( uniformsChanged ) in idRenderProgManager::CommitConstantBuffer.

**Pull request closed without merging**
