### PR TITLE
Fixed some Vulkan and DX12 validation layer errors / warnings

### PR DESCRIPTION
**Pull request by SRSaunders**
I haven't looked at the Vulkan & DX12 validation layer messages for a while, but went back today and have tried to clean them up for the Standard Profile (Vulkan) and make the game run under DX12 validation (was failing on errors before this).  Note that other specialized Vulkan profiles still yield warnings (Best Practices and Synchronization).

1. Removed conflicting `VkPhysicalDeviceBufferDeviceAddressFeaturesEXT` structure from `CreateDevice()` pNext chain.  This is not needed since we are using `VK_KHR_buffer_device_address`, not `VK_EXT_buffer_device_address`, and we are enabling the Vulkan 1.2 `BufferDeviceAddress` feature.
```
VUID-VkDeviceCreateInfo-pNext-pNext(ERROR / SPEC): msgNum: -1876993556 - Validation Error: [ VUID-VkDeviceCreateInfo-pNext-pNext ] Object 0: handle = 0x10f83b800, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x901f59ec | vkCreateDevice(): pCreateInfo->pNext<VkPhysicalDeviceBufferDeviceAddressFeaturesEXT> includes a pointer to a VkPhysicalDeviceBufferDeviceAddressFeaturesEXT, but when creating VkDevice, the parent extension (VK_EXT_buffer_device_address) was not included in ppEnabledExtensionNames. The Vulkan spec states: Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid struct for extending VkDeviceCreateInfo (https://vulkan.lunarg.com/doc/view/1.3.280.0/mac/1.3-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pNext-pNext)
    Objects: 1
        [0] 0x10f83b800, type: 1, name: NULL
```
2. Removed `VK_EXT_debug_utils` from Vulkan extensions since nvrhi does not use it.  Enable `VK_EXT_debug_marker` only when validation layer is enabled and set for `enableDebugRuntime` (i.e. when `VK_EXT_Debug_Report` is enabled).  Otherwise  we have a dependency problem between extensions.
```
VUID-vkCreateDevice-ppEnabledExtensionNames-01387(ERROR / SPEC): msgNum: 307460652 - Validation Error: [ VUID-vkCreateDevice-ppEnabledExtensionNames-01387 ] Object 0: handle = 0x10f83b800, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x12537a2c | vkCreateDevice(): pCreateInfo->ppEnabledExtensionNames[6] Missing extension required by the device extension VK_EXT_debug_marker: VK_EXT_debug_report. The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://vulkan.lunarg.com/doc/view/1.3.280.0/mac/1.3-extensions/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)
    Objects: 1
        [0] 0x10f83b800, type: 1, name: NULL
```
3. Suppressed Vulkan `[Shader-OutputNotConsumed]` validation warning when vertex shaders don't use all of their input layout parameters.  This is by design to simply and unify layouts, so don't need this message.
```
WARNING-Shader-OutputNotConsumed(WARN / PERF): msgNum: -937765618 - Validation Performance Warning: [ WARNING-Shader-OutputNotConsumed ] Object 0: handle = 0xa2eb680000000026, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0xc81ad50e | vkCreateGraphicsPipelines(): pCreateInfos[0].pVertexInputState Vertex attribute at location 2 not consumed by vertex shader.
    Objects: 1
        [0] 0xa2eb680000000026, type: 15, name: NULL
```
4. Suppressed DX12 fatal validation error `RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH`.  This is caused by cinematics and seems challenging to fix.  I have played with the barriers in the cinematic image upload code, but without success.  For now I have suppressed this message to permit the game to run with DX12 validation on.  Perhaps someone else can solve this cinematic barriers isssue properly.
```
D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Using ResourceBarrier on Command List (0x000002336599CA00:'Unnamed ID3D12GraphicsCommandList Object'): Before state (0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x0000023365345CC0:'_cinematic') (subresource: 0) specified by transition barrier does not match with the state (0xC0: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE|D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE) specified in the previous call to ResourceBarrier [ RESOURCE_MANIPULATION ERROR #527: RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH]
```
5. Suppressed DX12 validation warning `CLEARRENDERTARGETVIEW_MISMATCHINGCLEARVALUE`.  This is similar to the existing `D3D12_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_MISMATCHINGCLEARVALUE` which was already suppressed, so I felt this change was tolerable.
```
D3D12 WARNING: ID3D12CommandList::ClearRenderTargetView: The clear values do not match those passed to resource creation. The clear operation is typically slower as a result; but will still clear to the desired value. [ EXECUTION WARNING #820: CLEARRENDERTARGETVIEW_MISMATCHINGCLEARVALUE]
```
6. Fixed Vulkan and DX12 validation warnings when there are no framebuffer color attachments but there is a fragment shader configured in the pipeline (e.g. for the shadow atlas).  I added code to detect this condition and disable the fragment shader in these cases which in turn eliminates the warning conditions.
```
[Vulkan] WARNING location=0x9805298c code=0, layerPrefix='Validation'] Validation Warning: [ Undefined-Value-ShaderOutputNotConsumed ] Object 0: handle = 0xf9a524000000009e, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x9805298c | vkCreateGraphicsPipelines(): pCreateInfos[0] fragment shader writes to output location 0 with no matching attachment
```
```
D3D12 WARNING: ID3D12Device::CreateGraphicsPipelineState: The Pixel Shader expects a Render Target View bound to slot 0, but the PSO indicates that none will be bound. This is OK, as writes of an unbound Render Target View are discarded. It is also possible the developer knows the data will not be used anyway. This is only a problem if the developer actually intended to bind a Render Target View here. [ STATE_CREATION WARNING #679: CREATEGRAPHICSPIPELINESTATE_RENDERTARGETVIEW_NOT_SET]
```
7. Reported Vulkan Validation Layer defect which complained when a Debug Marker Object Name was added (by nvrhi) for swap chain images.  The Validation Layer was emitting false positives for this valid operation.  This is now fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7981.  Hopefully this will be included in the next SDK.
```
[Vulkan] ERROR location=0x4abd241d code=0, layerPrefix='Validation'] Validation Error: [ VUID-VkDebugMarkerObjectNameInfoEXT-object-01492 ] | MessageID = 0x4abd241d | vkDebugMarkerSetObjectNameEXT(): pNameInfo->objectType doesn't match the object. The Vulkan spec states: object must be a Vulkan object of the type associated with objectType as defined in VkDebugReportObjectTypeEXT and Vulkan Handle Relationship (https://vulkan.lunarg.com/doc/view/1.3.280.0/mac/1.3-extensions/vkspec.html#VUID-VkDebugMarkerObjectNameInfoEXT-object-01492)
```
8. Not Fixed:  There is one more issue reported by the Vulkan Validation Layer Synchronization Profile, that I would like to fix, but have not found it yet:
```
SYNC-HAZARD-WRITE-AFTER-WRITE(ERROR / SPEC): msgNum: 1544472022 - Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x1fb41e55f30, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x5c0ec5d6 | vkCmdClearColorImage():  Hazard WRITE_AFTER_WRITE for VkImage 0x1fb41e55f30[], range index 0. Access info (usage: SYNC_CLEAR_TRANSFER_WRITE, prior_usage: SYNC_CLEAR_TRANSFER_WRITE, write_barriers: 0, command: vkCmdClearColorImage, seq_no: 273, reset_no: 26783).
    Objects: 1
        [0] 0x1fb41e55f30, type: 10, name: NULL
```

Tested on Windows 10, Manjaro Linux, and macOS Ventura.

### CODE REVIEW

**Comment by RobertBeckebans** [comment]
What Vulkan SDK are you using on Windows 10?

1.
I get a different message ID for the shader parameter consumption warnings:
[Vulkan] PERFORMANCE WARNING location=0x609a13b code=0, layerPrefix='Validation'] Validation Performance Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0x7e6d0700000000f0, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | vertex shader writes to output location 0.0 which is not consumed by fragment shader. Enable VK_KHR_maintenance4 device extension to allow relaxed interface matching between input and output vectors.

So that is already on your branch and the messages aren't surpressed. Actually I had to add align the shader attributes to match the data passed by idDrawVert to get working pipeline state objects with Vulkan. It was really just for Vulkan while it was not necessary for OpenGL and DX12. This was also necessary in the old Vulkan backend or otherwise it would render spaghetti. It's kind of annoying that the validation layer warns about this.^

2.
Also VK_EXT_DEBUG_MARKER_EXTENSION_NAME needs to be added even when validation layers are not enabled. This is required by the commandList->beginMarker( szName ) stuff. Without it the markers are missing in RenderDoc.

Here is it with your current changes:
2024-05-11 10_44_37-RBDoom3BFG_2024 05 11_08 41 46_frame990 rdc - RenderDoc v1 29

This is how it looks if I add the VK_EXT_DEBUG_MARKER_EXTENSION_NAME back:
2024-05-11 10_53_05-RBDoom3BFG_2024 05 11_08 49 24_frame541 rdc - RenderDoc v1 29

3. I'm not sure about this. Even if there might be a warning depending on which validation layer is installed this seems to be incorrect. We always want the pixel shader to be executed even for the render targets that don't have a color attachment. In that case there is still a depth attachment and that one still requires a rasterizing state. I need to check this one further.
```
// SRS - if no color attachments (e.g. atlas), disable fragment shader to avoid validation warnings
	if( key.framebuffer->GetApiObject()->getDesc().colorAttachments.size() == 0 )
	{
		pipelineDesc.PS = nvrhi::ShaderHandle( NULL );
	}
```


Overall does it work for you to run +set r_useValidationLayers 2 and DX12? That one only works on my Geforce 2070 but it crashes on my laptop with the AMD RX 6800.

**Comment by RobertBeckebans** [comment]
Also forgot to mention that I made sure we don't run into validation errors by putting a breakpoint into

```
if( flags & VK_DEBUG_REPORT_ERROR_BIT_EXT )
		{
			idLib::Printf( "[Vulkan] ERROR location=0x%zx code=%d, layerPrefix='%s'] %s\n", location, code, layerPrefix, msg );
		}
```

while playing the game for a while. I haven't run into errors since the RBDoom 1.5.1 release.

**Comment by SRSaunders** [comment]
> What Vulkan SDK are you using on Windows 10?
I think it's 1.3.275.  I will update to 1.3.280 to recheck. A new one (1.3.283) should be coming out soon.

> I get a different message ID for the shader parameter consumption warnings:
Interesting.  I am running on an AMD 6600XT (like your laptop).  My warning is about an input issue, and yours is about an output issue.  I will recheck, but note that I tested with both r_useValidationLayers 2 and with vkconfig active as an override and got consistent messages.  I wonder if this is an NVidia difference?  I could add your message ID to the suppression list.

> Also VK_EXT_DEBUG_MARKER_EXTENSION_NAME needs to be added even when validation layers are not enabled
Interesting.  I was wondering about RenderDoc usage scenarios.  Do you want to run RenderDoc with validation off?  I suppose we could do the opposite, i.e. restore debug marker to be on all the time, and instead add debug report to the always on list (due to Vulkan extension dependencies).  However, I am not sure if this adds overhead during regular non-debugging execution.  I guess I thought you would be using RenderDoc with validation on.

> I'm not sure about this. Even if there might be a warning depending on which validation layer is installed this seems to be incorrect. We always want the pixel shader to be executed even for the render targets that don't have a color attachment. In that case there is still a depth attachment and that one still requires a rasterizing state.
Good feedback.  I will check this too and can revert if needed.  Please advise.

> Overall does it work for you to run +set r_useValidationLayers 2 and DX12?

It fails for me too (AMD GPU).  That's why I added suppression for RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH, which is caused by the way images are uploaded for the cinematics.  I would prefer to fix this one properly, but tried a bunch of barrier changes in the image upload code and couldn't figure it out.  Can you look at the core issue and try to fix?

Let me know about the above issues and I can add a commit that addresses your concerns.

**Comment by RobertBeckebans** [comment]
> I wonder if this is an NVidia difference? I could add your message ID to the suppression list.

The validation layer is part of the Vulkan SDK and not what the driver provides.

> Do you want to run RenderDoc with validation off?

Yes that was always the idea and having that extension enabled all shouldn't hurt the performance at all. It is guarded by r_logLevel > 1

**Comment by SRSaunders** [comment]
1. Thanks for your feedback on RenderDoc. Given this, I should revert the `VK_EXT_debug_marker` change but enable `VK_EXT_Debug_Report` all the time as a parent dependency.  This dependency and warning are evident if you turn on validation using the **vkconfig** tool (and not `r_useValidationLayers 2`).  The following message is issued if `VK_EXT_Debug_Report` is not enabled:

'VUID-vkCreateDevice-ppEnabledExtensionNames-01387(ERROR / SPEC): msgNum: 307460652 - Validation Error: [ VUID-vkCreateDevice-ppEnabledExtensionNames-01387 ] Object 0: handle = 0x10f83b800, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x12537a2c | vkCreateDevice(): pCreateInfo->ppEnabledExtensionNames[6] Missing extension required by the device extension VK_EXT_debug_marker: VK_EXT_debug_report. The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://vulkan.lunarg.com/doc/view/1.3.280.0/mac/1.3-extensions/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)'

Note that **nvrhi** tests for both of these extensions at setup time anyways.  I will make this change.

2. Regarding the shader consumption warnings, there are two cases of this that I have observed with my AMD setup:

i) On the vertex shader input layout side (e.g.if not using normal, tangent, or color2):
`[Vulkan] PERFORMANCE WARNING location=0xc81ad50e code=0, layerPrefix='Validation'] Validation Performance Warning: [ WARNING-Shader-OutputNotConsumed ] Object 0: handle = 0x470000000047, name = builtin/texture_color_sRGB:main, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0xc81ad50e | vkCreateGraphicsPipelines(): pCreateInfos[0].pVertexInputState Vertex attribute at location 2|3|5 not consumed by vertex shader.`
ii) On the fragment shader output side (for the atlas):
`[Vulkan] WARNING location=0x9805298c code=0, layerPrefix='Validation'] Validation Warning: [ Undefined-Value-ShaderOutputNotConsumed ] Object 0: handle = 0xf9a524000000009e, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x9805298c | vkCreateGraphicsPipelines(): pCreateInfos[0] fragment shader writes to output location 0 with no matching attachment`

I don't see the warning you mention above regarding vertex output to fragment input mismatches.  I do realize the validation layer is part of the SDK and indendent of the driver, but I am wondering whether its interactions/API with the driver can result in different messages depending on platform and GPU capabilities.  That's why I mentioned AMD vs. nVidia above.  However, neither the current master nor my branch enables `VK_KHR_maintenance4`.  I can add that in as an optional extension (not available on MoltenVK yet - it's currently in development) to see if it helps your situation.

3. Given your feedback re the no color attachment framebuffers (i.e. _shadowAtlas), I will revert this change.  In place I will try to add a suppression setting for Vulkan and DX12, since we know this condition is intentional.

**Comment by SRSaunders** [comment]
Changes complete.  Please let me know if these updates work for you.

**Comment by RobertBeckebans** [comment]
This is produced by C:\VulkanSDK\1.3.239.0

Interesting it says 
[Vulkan] PERFORMANCE WARNING location=0x609a13b code=0, layerPrefix='Validation'] Validation Performance Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0x5c5283000000003e, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | vertex shader writes to output location 1.0 which is not consumed by fragment shader. Enable VK_KHR_maintenance4 device extension to allow relaxed interface matching between input and output vectors.

but you already added VK_KHR_maintenance4 or is there something missing?^

I also still get a lot of 
[Vulkan] PERFORMANCE WARNING location=0x609a13b code=0, layerPrefix='Validation'] Validation Performance Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0xf9a524000000009e, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | Vertex attribute at location 2 not consumed by vertex shader^


Adding 0x609a13b to SetEnvironmentVariable( "VK_LAYER_MESSAGE_ID_FILTER", "0xc81ad50e;0x9805298c;0x609a13b" ) got rid of pretty much everything. It does not even trigger a breakpoint in vulkanDebugCallback anymore.

**Comment by SRSaunders** [comment]
Thanks very much for testing again, and the critical piece of information was Vulkan SDK 1.3.239.  I can finally duplicate your errors with this older version.

I will research a bit further, but it seems the VVL project has reworked the shader-related checks.  For instance, the older 0x609a13b messagid you are seeing now appears as 0xc81ad50e which is one of the ones I had already suppressed.  And the maintenance4 recommendation looks erroneous.

I will come back with one more commit to hopefully close this off.  I will likely revert the maintenance4 addition and add the 0x609a13b messagid (even though it is old), to handle cases when people are using an older SDK.

**Comment by SRSaunders** [comment]
It looks like the older Vulkan SDK 1.3.239 shader validation messages were generic with one messageID code (0x609a13b) covering a range of shader input/ouput warnings.  The more modern SDKs split these into multiple messageIDs.

Since these issues are by design with RBDoom3BFG, I added 0x609a13b to the suppression list for older SDKs and removed  `VK_KHR_maintenance4` since that change was not needed.

**Comment by RobertBeckebans** [comment]
Thanks for looking into this. This makes life definitely easier when analyzing problems in the renderer.

**Comment by SRSaunders** [comment]
Happy to help.

The one that bugs me is suppression for `D3D12_MESSAGE_ID_RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH`.  I tried to fix the underlying problem in the cinematics code vs suppression, but I seemed to be going in circles.  I had to suppress in the end because I was not getting anywhere.  Something to be aware of when you are testing new features or sync issues.  I wouldn't want suppression for the cinematics to cover up legit problems in other areas.

**Pull request merged**
