### PR TITLE
world muzzle flash lights enabled

### PR DESCRIPTION
**Pull request by y2keeth**
https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/7a2f275c174348bb754c35725fc3c1e9d15d3ebe

### CODE REVIEW

**Comment by BielBdeLuna** [comment]
great

**Comment by RobertBeckebans** [comment]
See comments for the commits

**Comment by y2keeth** [comment]
Thats odd, been running it and have not gotten the soulcube, nobody else has told me they have.  sorry if I did the code thing wrong, I still have no idea what I am doing on the site lol.  Just thought I'd try to give back.

**Comment by RobertBeckebans** [comment]
https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/59

Maybe it was fixed by other changes I did. I haven't tried it again

**Comment by y2keeth** [comment]
Mars underground, going to try that now.

**Comment by y2keeth** [comment]
Nope no Soulcube. You must have fixed that bug along the way.

**Comment by y2keeth** [comment]
about 479 people have this version and none of them said anything either, must be squashed lol.  What a weird bug from world lights code.

**Pull request merged**
