### PR TITLE
added a cvar to control the exposure of the filmgrain and also added a round bloom

### PR DESCRIPTION
**Pull request by BielBdeLuna**
I see you used "rpScreenCorrectionFactor" for passing several hdr parameters to the cg shaders, I uesed it too in order to pas the "exposure" from the cvar to the cg shader, would it be better practice to create a new parm in "renderParm_t" and use it to pass the info from the c++ code to the cg shaders?

besides all this, I also changed the bloom shader in order to get a round bluish bloom instead of the blue streak. what do you think of the round bloom?

### CODE REVIEW

**Comment by Yetta1** [comment]
@BielBdeLuna Are you referring to the blue lens flares? Because they become a bit overbearing, a value of 2-3 on the cvar looks nice. I think a round lens flare would be much better. Would it be possible for the lens flare to find it's colour source from the texture it's drawing from?

**Comment by BielBdeLuna** [comment]
yes, those blue strokes, i guess it could be done at the moment the colour as well as the way the samples fade is hardcoded in the shader, I guess it could be done with external images but I don't have enough knowledge to do this, today I just have learnt to pass values from the c++ code to the shaders :)

**Comment by Yetta1** [comment]
@BielBdeLuna Could the samples be picked like a colour picker from a graphics application through the shader, changing the hue based on the texture source?

**Comment by aFoxNamedMorris** [comment]
@BielBdeLuna Technicolor refers to the color properties of Technicolor brand chemical film: https://en.wikipedia.org/wiki/Technicolor

[img]http://edge.alluremedia.com.au/m/g/2015/08/blade_runner_3.jpg[/img]

**Comment by BielBdeLuna** [comment]
@aFoxNamedMorris I know what Technicolor was, but I find it a strange name, technicolor was a brand of tree strip black and white film-stock that made color possible through separating the light with the use of dichoric filters, from the 1930's to the 1950's then in the 70's it went out of business, and now it works as a colouring and color correcting facility in Hollywood. Blade Runner wasn't shot on Technicolor but on non-speedy film-stock (35mm Kodak 5247 100T) form the 80's.
So that's the reason for my question why that name? :)

**Comment by RobertBeckebans** [comment]
I simply ripped it off from Sweet-FX:
https://delightlylinux.wordpress.com/2014/01/21/sweetfx-technicolor/

2015-12-29 17:37 GMT+01:00 Biel Bestué de Luna <notifications@github.com>:

**Comment by Yetta1** [comment]
Blender has a nice selection to mimic film colouring effects. Not sure if it can be ported over. It's under the color management menu, there you can also select raw, film, rrt and logarithmic outputs for the image as well as tweak gamma and exposure. A selection would be nice, as some apply well to certain scenes, where others wouldn't.

**Pull request closed without merging**
