### PR TITLE
Linux users can get the game data with native Steam

### PR DESCRIPTION
**Pull request by Tea23**

### CODE REVIEW

**Comment by DanielGibson** [comment]
awesome!

**Comment by Tea23** [comment]
I should proofread. Path should be:
`~/.steam/root/ubuntu12_32/steamapps/content/app_208200/depot_208202/` `/common/`

**Comment by RobertBeckebans** [comment]
Very nice.

2015-03-26 1:15 GMT+01:00 Joe <notifications@github.com>:

**Comment by xDShot** [comment]
Actually you can use SteamCMD for downloading content too!

**Pull request merged**
