### PR TITLE
Support SDL2 GameController API

### PR DESCRIPTION
**Pull request by vivkin**
On OS X DualShock4 works perfectly

### CODE REVIEW

**Comment by RobertBeckebans** [comment]
Thanks for your effort. I still need to test this.

**Comment by BielBdeLuna** [comment]
on Ubuntu, this seems to have solved the dualshock3 input on GUIs but in-game it seems to stay inert, only the select button work ( it brings the game menu, like the escape in the keyboard ) I've been looking at the sdl_events and it seems that the input is differentiated between the GUIs and the ingame, is there anything that can be done so the gamepad works also ingame?

**Comment by BielBdeLuna** [comment]
i get the following message: 
```
GameController 0 name: PS3 Controller
GameController 0 is mapped as "030000004c0500006802000011010000,PS3 Controller,a:b14,b:b13,back:b0,dpdown:b6,dpleft:b7,dpright:b5,dpup:b4,guide:b16,leftshoulder:b10,leftstick:b1,lefttrigger:b8,leftx:a0,lefty:a1,rightshoulder:b11,rightstick:b2,righttrigger:b9,rightx:a2,righty:a3,start:b3,x:b15,y:b12,"
```

I see the names of the actions but what are the "b-something" that comes afterwards?

**Comment by BielBdeLuna** [comment]
I think we also should consider this other solution: https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/314

**Pull request merged**
