### PR TITLE
Enable VK_KHR_portability_enumeration for macOS on Vulkan SDK 1.3.211.0 or later

### PR DESCRIPTION
**Pull request by SRSaunders**
The Vulkan SDK 1.3.211.0 loader has implemented VK_KHR_portability_enumeration which requires the instance extension `VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME`, and the `VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR` flag bit to be set in `VkInstanceCreateInfo` when calling `vkCreateInstance()`.  Otherwise the MoltenVK portability driver may not be enumerated as an available Vulkan device.  This pull request enables the instance extension and flag when available in the Vulkan SDK for the macOS portability implementation.  A compiler directive guards this code to prevent build failures on earlier SDKs that did not define or require this extension.

Also moved the fix for issue #656 allowing deprecated Vulkan version macro compatibility for older Vulkan SDKs <  1.2.176 (i.e. `VK_VERSION_MAJOR` vs. `VK_API_VERSION_MAJOR`, etc) to this smaller Vulkan-specific pull request.

Note that as of Vulkan SDK 1.3.211.0 and MoltenVK 1.1.9, the `maxSamplerAllocationCount` limit has been lifted and the Vulkan loader should no longer report validation errors during game level loads when creating thousands of samplers on macOS MoltenVK.  This was previously an annoying issue, but thanks to @billhollings the issue is now solved.  See https://github.com/KhronosGroup/MoltenVK/issues/1512 for more details if interested.

### CODE REVIEW

**Review by runlevel5 — APPROVED** [review]
LGTM 👍

**Comment by SRSaunders** [comment]
FYI - This should be merged into master asap.  Otherwise game will not run on macOS using current MoltenVK versions.

**Comment by RobertBeckebans** [comment]
I recently worked on the NVRHI Vulkan backend. There are still some issues to be sorted out but it seems to be that it will have feature parity with the new DX12 backend. The menu already works and even shadow mapping, rendering PBR lightgrid to HDR offscreen framebuffers. Basically everything the old Vulkan backend is lacking compared to OpenGL. Once I get it working then I will deprecate the old OpenGL and Vulkan backends and disable them from CMake configuration because we don't want to write new shaders for the old backends and there are 2 complete different sets of shaders right now.

**Comment by SRSaunders** [comment]
Hi Robert, sorry for the slow reply, but I have been experimenting with your 635-nvrhi3 branch.  I have created a derivative branch in my repo (called 635-nvrhi-sdl) that implements an SDL backend for NVRHI, targeting linux and macOS.  I have it working on macOS+MoltenVK up to the Doom3/Classic game select screen, but it crashes when moving into the main menu screen for any game, Doom3 or Classic.  I have tested the same code on linux but it crashes on that platform too after the intro video.  Just for comparison, I compiled your 635-nvrhi branch for Windows Vulkan on my test box and, while I can enter the main menu, it also crashes when using the NVRHI Vulkan backend on loading a game.  I am using an AMD 6600XT graphics card for my tests with up-to-date drivers.  Are there any additional branch merges or setup configs that are required to run the game using NVRHI on Vulkan?

If I turn on validation (=2) Vulkan throws very similar errors on all platforms, and while this is encouraging, I suspect each platform may have different sensitivities to the errors.  The key validation errors I see are:
1. _vkCmdPipelineBarrier(): .srcStageMask must not be 0 unless synchronization2 is enabled. The Vulkan spec states: If the synchronization2 feature is not enabled, pname:srcStageMask must not be 0_
2. _vkCmdDrawIndexed: This call must be issued inside an active render pass. The Vulkan spec states: This command must only be called inside of a render pass instance_

As far as I know you are not using Vulkan's synchronization2 for the game, so something odd is happening inside NVRHI for all platforms regrind the srcStageMask.  However, I do suspect the root cause may be synchronization and/or resource management-related.  On macOS, the application dies after hitting the second error above (i.e. drawing outside of a render pass).  Looking at the game code I don't see how this can happen, so I suspect NVRHI is not managing the render passes correctly, possibly caused by bad synchronization.

Other observations from my SDL port:

1. Clang 14 with C++17 enabled does not like the `register` keyword - it is fully deprecated and removed from the C++17 language standard.  I am not sure how MSVC handles it, but I had to remove `register` from the code (mostly in the jpeg-6 stuff, but a few other places as well).
2. gcc 12.2 on linux would not compile NVRHI without errors.  I had to switch to Clang 14 on my Manjaro box.
3. Clang requires a few more explicit type casts than does MSVC, so I added those in the code.
4. I had to disable parallel shader compilation, as I was getting random shader compilation failures on macOS.
5. I reinstated VULKAN_USE_PLATFORM_SDL (for the platform windowing system) since it is orthogonal to USE_VULKAN (for the legacy backend).
6. Fixed builtins/VR/... case sensitivity on linux.  Not an issue for Windows or macOS.
7. Aligned DeviceManager_VK.cpp between Windows and SDL platforms - works for both.  A single file could be used to simplify maintenance (and possibly moved up a directory level to neo/sys vs neo/sys/win32 or neo/sys/sdl).
8. Regarding macOS specifics, a possibly larger issue is that while MoltenVK implements the Vulkan 1.2 features needed for the game, it does not currently support Geometry Shaders.  I see you have disabled the Geometry pass in your 635-nvrhi3 branch and thus the NVRHI version should run on the Mac for now, but don't know your plans for the future or if this pass can be kept optional.

In any case, if you are interested in my changes, you could look at my 635-nvrhi-sdl branch.

**Comment by RobertBeckebans** [comment]
That is awesome. I merged your branch into 635-nvrhi3.
I disabled timer queries and SSAO it can boot into a game but there are definitely some Vulkan errors left.

Regarding your points

2. I only tested the NVRHI donut samples with clang on Linux. I personally don't really care about gcc and if clang works then it's enough
9. Actually for releases the shader binaries should be in base/renderprogs2/ next to the other game data. There are more and more people interested in making content with the engine. It is the best under Linux to work within the git repo clone where also the other data for the tools like base/materials/*.mtr exist. People should copy the Steam data to that base/ folder and run it from the git clone. Right now it uses idFilesystem::ReadFile which should do the local lookup instead of reading from the home dir.
10. The entire idea of the NVRHI backend is to reduce the maintenance costs and to move the renderer into a new generation where we can benefit from hardware raytracing. Raytracing should be optional but it will be a productivity booster for all people who want to develop games with this engine. I want to clean up the code and remove the legacy code within the renderer so other programmers aren't afraid of all those multiple render paths. OpenGL is dead and Vulkan is actually a really nasty API. NVRHI is as easy as OpenGL but we might need to fix some stuff to get the BFG renderer running ok. The old Vulkan backend was never feature complete so it should be abandoned.

If you have more issues then please report them to https://github.com/RobertBeckebans/RBDOOM-3-BFG/projects/8

**Comment by SRSaunders** [comment]
I'm happy that you found this useful and merged the changes.  To compile on linux with clang you will need to merge your latest master branch containing commit 56a10e713638af6f1bb94f6fbf3ddfd4818e7379.

Unfortunately, even with timer queries and SSAO disabled the app still dies on macOS with the errors above - trying to draw outside of a render pass.  I will try linux Manjaro later this evening.  Something may still be still wrong.

FYI - The reason I disabled USE_NVRHI_VULKAN by default was to be compatible with older cmake scripts that use the legacy backends.  However, if your 635-nvrhi3 branch will never support those backends or scripts it no longer matters.  I could clean up the UNIX path in the CMakeLists file if you want.

Last thing - on macOS I had to make one change to nvrhi/tools/shaderCompiler/CMakeLists.txt, disabling `stdc++fs` in `target_link_libraries()`.  It is not needed for AppleClang and will not link.  I am not sure how we could solve this issue as it is outside of your game repository.  Any ideas?

**Comment by RobertBeckebans** [comment]
You can make a pull request for that nvrhi/tools change against the official Nvidia repo and I merge it into my clone until it's in the official branch.

**Pull request merged**
