### PR TITLE
Capture mouse properly on macOS when outside of window, fixes issue #584

### PR DESCRIPTION
**Pull request by SRSaunders**
Fixes macOS issue where mouse was not captured properly and window boundary was not respected.  This would happen after console is closed with mouse outside of game window.  Setting SDL2 hint to use mouse warping when relative mouse mode is enabled fixes issue #584.  This is set up once per session in either GLimp_Init() for OpenGL or VKimp_Init() for Vulkan.

Also removed unneeded cmake-macos-opengl-debug.sh and cmake-macos-vulkan-debug.sh shell scripts.  On macOS should be using Xcode versions for debug builds and debugging.  Reduces future script maintenance.  Added doc comments to cmake-xcode-vulkan-*.sh shell scripts for Xcode Vulkan builds.

Made a small CMakeLists.txt improvement to how macOS sysroot is checked and added to the build definitions.  Improves command line build flexibility and robustness by separating and independently checking the cmake variable definitions for: a) macOS sysroot (CMAKE_OSX_SYSROOT ) and b) macOS min deployment target (CMAKE_OSX_DEPLOYMENT_TARGET).  This fixes command line build failures in certain setups where sysroot was not properly defined.

Above changes are limited to macOS-specific code.

Also fixed 2 compiler-related issues for clang and gcc:

a) Removed `-fno-unsafe-math-optimizations` compiler option on release builds since this is already the default for gcc & clang.  Eliminates conflicts with `-fno-trapping-math` option which can cause build warnings with clang 12 (macOS Big Sur).  This matches change made to dhewm3 build.  Ref discussion in pull request #575.

b) Fixed build failure with gcc 11 caused by string length overflow checking as described in issues #552 and #587 .

Updated README with macOS build instructions, plus a few installation edits.

### CODE REVIEW

**Review by BielBdeLuna — CHANGES_REQUESTED** [review]
This change maybe should be specified for Clang only but for GCC leave the -fno-unsafe-math-optimizations flag on, because without it in GCC we'll get the dmap error again.

**Comment by SRSaunders** [comment]
Strange, since `-fno-unsafe-math-optimizations` is already the default for gcc (and clang).  This change should have no effect.  See final discussion re dhewm3 in #575.  The option should have only been necessary if `-ffast-math` is specified, which is no longer the case.  Did you run the dmap test without this option and get a failure?

**Comment by BielBdeLuna** [comment]
oh sorry it's true, I mixed `-fno-unsafe-math-optimizations` with `-ffp-contract=off`, ignore my dumb comment :)

**Comment by SRSaunders** [comment]
Thanks for the clarification, and no issues re your comment.  I'm happy that you looked at this thread and reviewed.  You did a lot of work to solve the dmap error via `-ffp-contract=off` and I wouldn't want to do anything to break that.

**Pull request merged**
